apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: omr21/api-gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: AUTH_SERVICE_URL
              value: http://auth-service:4001
            - name: PRODUCT_SERVICE_URL
              value: http://product-service:4002
            - name: ORDER_SERVICE_URL
              value: http://order-service:4003
            - name: SUPPLIER_SERVICE_URL
              value: http://supplier-service:4004
            - name: NOTIFICATION_SERVICE_URL
              value: http://notification-service:4005
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: smart-inventory-secrets
                  key: JWT_SECRET

