apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: mahmoud416/product-service:latest
          ports:
            - containerPort: 4002
          env:
            - name: PORT
              value: "4002"
            - name: MONGO_URI
              value: mongodb://mongo:27017/product_db
